In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
transaction = pd.read_excel("Transaction.xlsx")

In [3]:
transaction.head()

,TransactionId,UserId,VisitYear,VisitMonth,VisitMode,AttractionId,Rating
0,3,70456,2022,10,2,640,5
1,8,7567,2022,10,4,640,5
2,9,79069,2022,10,3,640,5
3,10,31019,2022,10,3,640,3
4,15,43611,2022,10,2,640,3

In [4]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TransactionId  52930 non-null  int64
 1   UserId         52930 non-null  int64
 2   VisitYear      52930 non-null  int64
 3   VisitMonth     52930 non-null  int64
 4   VisitMode      52930 non-null  int64
 5   AttractionId   52930 non-null  int64
 6   Rating         52930 non-null  int64
dtypes: int64(7)
memory usage: 2.8 MB

In [5]:
transaction.shape

(52930, 7)

In [6]:
transaction.isnull().sum()

TransactionId    0
UserId           0
VisitYear        0
VisitMonth       0
VisitMode        0
AttractionId     0
Rating           0
dtype: int64

In [7]:
transaction.duplicated().sum()

0

In [8]:
transaction["Rating"].value_counts().sort_index()

Rating
1     1263
2     2035
3     7730
4    17966
5    23936
Name: count, dtype: int64

In [9]:
transaction["VisitMode"].value_counts()

VisitMode
2    21620
3    15217
4    10945
5     4525
1      623
Name: count, dtype: int64

In [10]:
transaction["VisitYear"].value_counts().sort_index()

VisitYear
2013     2983
2014     4808
2015     8687
2016    12823
2017     9444
2018     7461
2019     5913
2020      529
2021       35
2022      247
Name: count, dtype: int64

In [11]:
transaction["VisitMonth"].value_counts().sort_index()

VisitMonth
1     4458
2     3671
3     3772
4     4445
5     4316
6     4361
7     4861
8     5026
9     4917
10    4715
11    3846
12    4542
Name: count, dtype: int64

In [12]:
print("Unique Users:", transaction["UserId"].nunique())
print("Unique Attractions:", transaction["AttractionId"].nunique())

print("\nUserId range:")
print(transaction["UserId"].min(), "to", transaction["UserId"].max())

print("\nAttractionId range:")
print(transaction["AttractionId"].min(), "to", transaction["AttractionId"].max())

Unique Users: 33530
Unique Attractions: 30

UserId range:
14 to 88190

AttractionId range:
369 to 1297

In [13]:
user = pd.read_excel("User.xlsx")

In [14]:
user.head()

   UserId  ContinentId  RegionId  CountryId  CityId
0      14            5        20        155   220.0
1      16            3        14        101  3098.0
2      20            4        15        109  4303.0
3      23            1         4         22   154.0
4      25            3        14        101  3098.0

In [15]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33530 entries, 0 to 33529
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   UserId       33530 non-null  int64
 1   ContinentId  33530 non-null  int64
 2   RegionId     33530 non-null  int64
 3   CountryId    33530 non-null  int64
 4   CityId       33526 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 1.3 MB

In [16]:
user.isnull().sum()

UserId         0
ContinentId    0
RegionId       0
CountryId      0
CityId         4
dtype: int64

In [17]:
city = pd.read_excel("City.xlsx")

In [18]:
city.head()

   CityId      CityName  CountryId
0       0             -          0
1       1        Douala          1
2       2  South Region          1
3       3     N'Djamena          2
4       4        Kigali          3

In [19]:
city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9143 entries, 0 to 9142
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CityId     9143 non-null   int64
 1   CityName   9142 non-null   object
 2   CountryId  9143 non-null   int64
dtypes: int64(2), object(1)
memory usage: 214.4+ KB

In [20]:
city.isnull().sum()

CityId       0
CityName     1
CountryId    0
dtype: int64

In [21]:
country = pd.read_excel("Country.xlsx")

In [22]:
country.head()

   CountryId   Country  RegionId
0          0         -         0
1          1  Cameroon         1
2          2      Chad         1
3          3    Rwanda         1
4          4  Ethiopia         2

In [23]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CountryId  165 non-null    int64
 1   Country    165 non-null    object
 2   RegionId   165 non-null    int64
dtypes: int64(2), object(1)
memory usage: 4.0+ KB

In [24]:
country.isnull().sum()

CountryId    0
Country      0
RegionId     0
dtype: int64

In [25]:
region = pd.read_excel("Region.xlsx")

In [26]:
region.head()

            Region  RegionId  ContinentId
0                -         0            0
1   Central Africa         1            1
2      East Africa         2            1
3     North Africa         3            1
4  Southern Africa         4            1

In [27]:
region.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Region       22 non-null     object
 1   RegionId     22 non-null     int64
 2   ContinentId  22 non-null     int64
dtypes: int64(2), object(1)
memory usage: 660.0+ bytes

In [28]:
region.isnull().sum()

Region         0
RegionId       0
ContinentId    0
dtype: int64

In [29]:
continent = pd.read_excel("Continent.xlsx")

In [30]:
continent.head()

   ContinentId            Continent
0            0                    -
1            1               Africa
2            2              America
3            3                 Asia
4            4  Australia & Oceania

In [31]:
continent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ContinentId  6 non-null      int64
 1   Continent    6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [32]:
continent.isnull().sum()

ContinentId    0
Continent      0
dtype: int64

In [33]:
mode = pd.read_excel("Mode.xlsx")

In [34]:
mode.head()

   VisitModeId VisitMode
0            0         -
1            1  Business
2            2   Couples
3            3    Family
4            4   Friends

In [35]:
mode.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   VisitModeId  6 non-null      int64
 1   VisitMode    6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [36]:
mode.isnull().sum()

VisitModeId    0
VisitMode      0
dtype: int64

In [37]:
type_df = pd.read_excel("Type.xlsx")

In [38]:
type_df.head()

   AttractionTypeId         AttractionType
0                 2          Ancient Ruins
1                10                Ballets
2                13                Beaches
3                19        Caverns & Caves
4                34  Flea & Street Markets

In [39]:
type_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AttractionTypeId  17 non-null     int64
 1   AttractionType    17 non-null     object
dtypes: int64(1), object(1)
memory usage: 404.0+ bytes

In [40]:
type_df.isnull().sum()

AttractionTypeId    0
AttractionType      0
dtype: int64

In [41]:
item = pd.read_excel("Item.xlsx")

In [42]:
item.head()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
0,369,1,13,Kuta Beach - Bali,Kuta
1,481,1,13,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia"
2,640,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia"
3,650,1,13,Sanur Beach,Sanur
4,673,1,13,Seminyak Beach,Seminyak

In [43]:
item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AttractionId       30 non-null     int64
 1   AttractionCityId   30 non-null     int64
 2   AttractionTypeId   30 non-null     int64
 3   Attraction         30 non-null     object
 4   AttractionAddress  30 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.3+ KB

In [44]:
item.isnull().sum()

AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64

In [45]:
updated_item = pd.read_excel("Updated_Item.xlsx")

In [46]:
updated_item.head()

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
0,369,1,13,Kuta Beach - Bali,Kuta
1,481,1,13,Nusa Dua Beach,"Semenanjung Nusa Dua, Nusa Dua 80517 Indonesia"
2,640,1,63,Sacred Monkey Forest Sanctuary,"Jl. Monkey Forest, Ubud 80571 Indonesia"
3,650,1,13,Sanur Beach,Sanur
4,673,1,13,Seminyak Beach,Seminyak

In [47]:
print("Original Item.xlsx:")
print(item.shape)

print("\nUpdated_Item.xlsx:")
print(updated_item.shape)

print("\nOriginal columns:")
print(item.columns.tolist())

print("\nUpdated columns:")
print(updated_item.columns.tolist())

Original Item.xlsx:
(30, 5)

Updated_Item.xlsx:
(1698, 5)

Original columns:
['AttractionId', 'AttractionCityId', 'AttractionTypeId', 'Attraction', 'AttractionAddress']

Updated columns:
['AttractionId', 'AttractionCityId', 'AttractionTypeId', 'Attraction', 'AttractionAddress']

In [48]:
item = updated_item.copy()

In [49]:
item.shape

(1698, 5)

In [50]:
item.duplicated().sum()

0

In [51]:
user.duplicated().sum()

0

In [52]:
city.duplicated().sum()

0

In [53]:
country.duplicated().sum()

0

In [54]:
region.duplicated().sum()

0

In [55]:
continent.duplicated().sum()

0

In [56]:
mode.duplicated().sum()

0

In [57]:
type_df.duplicated().sum()

0

In [58]:
continent["ContinentId"].duplicated().sum()

0

In [59]:
country["CountryId"].duplicated().sum()

0

In [60]:
region["RegionId"].duplicated().sum()

0

In [61]:
city["CityId"].duplicated().sum()

0

In [62]:
mode["VisitModeId"].duplicated().sum()

0

In [63]:
type_df["AttractionTypeId"].duplicated().sum()

0

In [64]:
item["AttractionId"].duplicated().sum()

0

In [65]:
item.isnull().sum()

AttractionId         0
AttractionCityId     0
AttractionTypeId     0
Attraction           0
AttractionAddress    0
dtype: int64

In [66]:
print("City:")
print(city.isnull().sum())

print("\nCountry:")
print(country.isnull().sum())

print("\nRegion:")
print(region.isnull().sum())

print("\nContinent:")
print(continent.isnull().sum())

print("\nMode:")
print(mode.isnull().sum())

print("\nType:")
print(type_df.isnull().sum())

City:
CityId       0
CityName     1
CountryId    0
dtype: int64

Country:
CountryId    0
Country      0
RegionId     0
dtype: int64

Region:
Region         0
RegionId       0
ContinentId    0
dtype: int64

Continent:
ContinentId    0
Continent      0
dtype: int64

Mode:
VisitModeId    0
VisitMode      0
dtype: int64

Type:
AttractionTypeId    0
AttractionType      0
dtype: int64

In [67]:
city[city["CityName"].isnull()]

      CityId CityName  CountryId
6879    6879      NaN        151

In [68]:
city["CityName"] = city["CityName"].fillna("Unknown City")

In [69]:
city.isnull().sum()

CityId       0
CityName     0
CountryId    0
dtype: int64

In [70]:
missing_users = set(transaction["UserId"]) - set(user["UserId"])

print("User IDs in Transaction:", transaction["UserId"].nunique())
print("User IDs in User dataset:", user["UserId"].nunique())
print("Transaction User IDs not found in User dataset:", len(missing_users))

User IDs in Transaction: 33530
User IDs in User dataset: 33530
Transaction User IDs not found in User dataset: 0

In [71]:
missing_attractions = set(transaction["AttractionId"]) - set(item["AttractionId"])

print("Attraction IDs in Transaction:", transaction["AttractionId"].nunique())
print("Attraction IDs in Item dataset:", item["AttractionId"].nunique())
print("Transaction Attraction IDs not found in Item dataset:", len(missing_attractions))

Attraction IDs in Transaction: 30
Attraction IDs in Item dataset: 1698
Transaction Attraction IDs not found in Item dataset: 0

In [72]:
print("VisitMode values in Transaction:")
print(transaction["VisitMode"].unique())

print("\nVisitMode values in Mode dataset:")
print(mode["VisitMode"].unique())

VisitMode values in Transaction:
[2 4 3 5 1]

VisitMode values in Mode dataset:
['-' 'Business' 'Couples' 'Family' 'Friends' 'Solo']

In [73]:
mode

   VisitModeId VisitMode
0            0         -
1            1  Business
2            2   Couples
3            3    Family
4            4   Friends
5            5      Solo

In [74]:
print("Attraction Type IDs in Item:")
print(item["AttractionTypeId"].unique())

print("\nAttraction Type IDs in Type dataset:")
print(type_df["AttractionTypeId"].unique())

Attraction Type IDs in Item:
[13 63 76 72 93 92 61 64 82 91 84 19 34 10 2 45 44 'Temple' 'Beach' 'Park'
 'Museum' 'Market']

Attraction Type IDs in Type dataset:
[ 2 10 13 19 34 44 45 61 63 64 72 76 82 84 91 92 93]

In [75]:
item[item["AttractionTypeId"].apply(lambda x: isinstance(x, str))]

,AttractionId,AttractionCityId,AttractionTypeId,Attraction,AttractionAddress
30,1298,0,Temple,Ancient Temple - -,"Main Street, -, -"
31,1299,0,Beach,Paradise Beach - -,"Main Street, -, -"
32,1300,0,Park,National Park - -,"Main Street, -, -"
33,1301,0,Museum,Cultural Heritage Center - -,"Main Street, -, -"
34,1302,2,Museum,Art Gallery - South Region,"Main Street, South Region, Cameroon"
...,...,...,...,...,...
1693,2961,8154,Temple,Ancient Temple - Churchdown,"Main Street, Churchdown, United Kingdom"
1694,2962,9142,Temple,Ancient Temple - Sanaa,"Main Street, Sanaa, Yemen"
1695,2963,9142,Museum,Science Museum - Sanaa,"Main Street, Sanaa, Yemen"
1696,2964,9142,Park,Botanical Garden - Sanaa,"Main Street, Sanaa, Yemen"
1697,2965,9142,Park,Botanical Garden - Sanaa,"Main Street, Sanaa, Yemen"

In [76]:
type_df.sort_values("AttractionTypeId")

    AttractionTypeId                  AttractionType
0                  2                   Ancient Ruins
1                 10                         Ballets
2                 13                         Beaches
3                 19                 Caverns & Caves
4                 34           Flea & Street Markets
5                 44                  Historic Sites
6                 45                 History Museums
7                 61                  National Parks
8                 63         Nature & Wildlife Areas
9                 64                   Neighborhoods
10                72  Points of Interest & Landmarks
11                76                 Religious Sites
12                82                            Spas
13                84              Speciality Museums
14                91                        Volcanos
15                92                     Water Parks
16                93                      Waterfalls

In [77]:
item[item["AttractionTypeId"].apply(lambda x: isinstance(x, str))]["AttractionTypeId"].value_counts()

AttractionTypeId
Museum    367
Temple    340
Market    325
Beach     318
Park      318
Name: count, dtype: int64

In [78]:
item["AttractionTypeClean"] = item["AttractionTypeId"].astype(str)

In [79]:
item[["AttractionTypeId", "AttractionTypeClean"]].head(10)

  AttractionTypeId AttractionTypeClean
0               13                  13
1               13                  13
2               63                  63
3               13                  13
4               13                  13
5               76                  76
6               72                  72
7               93                  93
8               76                  76
9               92                  92

In [80]:
print("Missing values:", item["AttractionTypeClean"].isnull().sum())

print("\nUnique attraction types:")
print(item["AttractionTypeClean"].value_counts())

Missing values: 0

Unique attraction types:
AttractionTypeClean
Museum    367
Temple    340
Market    325
Park      318
Beach     318
13          6
72          3
61          2
91          2
63          2
2           2
93          2
76          2
64          1
82          1
84          1
34          1
10          1
45          1
44          1
92          1
19          1
Name: count, dtype: int64

In [81]:
missing_cities = set(item["AttractionCityId"]) - set(city["CityId"])

print("Attraction City IDs:", item["AttractionCityId"].nunique())
print("City IDs in City dataset:", city["CityId"].nunique())
print("Attraction City IDs not found in City dataset:", len(missing_cities))

Attraction City IDs: 417
City IDs in City dataset: 9143
Attraction City IDs not found in City dataset: 0

In [82]:
missing_countries = set(city["CountryId"]) - set(country["CountryId"])

print("Country IDs in City:", city["CountryId"].nunique())
print("Country IDs in Country dataset:", country["CountryId"].nunique())
print("City Country IDs not found in Country dataset:", len(missing_countries))

Country IDs in City: 164
Country IDs in Country dataset: 165
City Country IDs not found in Country dataset: 0

In [83]:
missing_regions = set(country["RegionId"]) - set(region["RegionId"])

print("Region IDs in Country:", country["RegionId"].nunique())
print("Region IDs in Region dataset:", region["RegionId"].nunique())
print("Country Region IDs not found in Region dataset:", len(missing_regions))

Region IDs in Country: 22
Region IDs in Region dataset: 22
Country Region IDs not found in Region dataset: 0

In [84]:
missing_continents = set(region["ContinentId"]) - set(continent["ContinentId"])

print("Continent IDs in Region:", region["ContinentId"].nunique())
print("Continent IDs in Continent dataset:", continent["ContinentId"].nunique())
print("Region Continent IDs not found in Continent dataset:", len(missing_continents))

Continent IDs in Region: 6
Continent IDs in Continent dataset: 6
Region Continent IDs not found in Continent dataset: 0

In [85]:
numeric_type_ids = set(
    item.loc[
        pd.to_numeric(item["AttractionTypeId"], errors="coerce").notna(),
        "AttractionTypeId"
    ].astype(int)
)

type_ids = set(type_df["AttractionTypeId"])

missing_types = numeric_type_ids - type_ids

print("Numeric AttractionTypeIds in Item:", sorted(numeric_type_ids))
print("AttractionTypeIds in Type:", sorted(type_ids))
print("Numeric IDs not found in Type:", missing_types)

Numeric AttractionTypeIds in Item: [2, 10, 13, 19, 34, 44, 45, 61, 63, 64, 72, 76, 82, 84, 91, 92, 93]
AttractionTypeIds in Type: [2, 10, 13, 19, 34, 44, 45, 61, 63, 64, 72, 76, 82, 84, 91, 92, 93]
Numeric IDs not found in Type: set()

In [86]:
print("Minimum Rating:", transaction["Rating"].min())
print("Maximum Rating:", transaction["Rating"].max())

print("\nRatings outside 1-5:")
print(transaction[
    (transaction["Rating"] < 1) |
    (transaction["Rating"] > 5)
])

Minimum Rating: 1
Maximum Rating: 5

Ratings outside 1-5:
Empty DataFrame
Columns: [TransactionId, UserId, VisitYear, VisitMonth, VisitMode, AttractionId, Rating]
Index: []

In [87]:
print("Total transactions:", len(transaction))
print("Unique Transaction IDs:", transaction["TransactionId"].nunique())
print("Duplicate Transaction IDs:", transaction["TransactionId"].duplicated().sum())

Total transactions: 52930
Unique Transaction IDs: 52930
Duplicate Transaction IDs: 0

In [88]:
print("Total user rows:", len(user))
print("Unique User IDs:", user["UserId"].nunique())
print("Duplicate User IDs:", user["UserId"].duplicated().sum())

Total user rows: 33530
Unique User IDs: 33530
Duplicate User IDs: 0

In [89]:
print("Total city rows:", len(city))
print("Unique City IDs:", city["CityId"].nunique())
print("Duplicate City IDs:", city["CityId"].duplicated().sum())

Total city rows: 9143
Unique City IDs: 9143
Duplicate City IDs: 0

In [90]:
print("Total country rows:", len(country))
print("Unique Country IDs:", country["CountryId"].nunique())
print("Duplicate Country IDs:", country["CountryId"].duplicated().sum())

Total country rows: 165
Unique Country IDs: 165
Duplicate Country IDs: 0

In [91]:
print("Total region rows:", len(region))
print("Unique Region IDs:", region["RegionId"].nunique())
print("Duplicate Region IDs:", region["RegionId"].duplicated().sum())

Total region rows: 22
Unique Region IDs: 22
Duplicate Region IDs: 0

In [92]:
print("Total region rows:", len(region))
print("Unique Region IDs:", region["RegionId"].nunique())
print("Duplicate Region IDs:", region["RegionId"].duplicated().sum())

Total region rows: 22
Unique Region IDs: 22
Duplicate Region IDs: 0

In [93]:
print("Total continent rows:", len(continent))
print("Unique Continent IDs:", continent["ContinentId"].nunique())
print("Duplicate Continent IDs:", continent["ContinentId"].duplicated().sum())

Total continent rows: 6
Unique Continent IDs: 6
Duplicate Continent IDs: 0

In [94]:
print("Total mode rows:", len(mode))
print("Unique VisitMode IDs:", mode["VisitModeId"].nunique())
print("Duplicate VisitMode IDs:", mode["VisitModeId"].duplicated().sum())

Total mode rows: 6
Unique VisitMode IDs: 6
Duplicate VisitMode IDs: 0

In [95]:
print("Total type rows:", len(type_df))
print("Unique Attraction Type IDs:", type_df["AttractionTypeId"].nunique())
print("Duplicate Attraction Type IDs:", type_df["AttractionTypeId"].duplicated().sum())

Total type rows: 17
Unique Attraction Type IDs: 17
Duplicate Attraction Type IDs: 0

In [96]:
numeric_type_ids = pd.to_numeric(
    item["AttractionTypeId"], errors="coerce"
).dropna().unique()

missing_type_ids = set(numeric_type_ids) - set(type_df["AttractionTypeId"])

print("Numeric type IDs in Item:", sorted(numeric_type_ids))
print("Missing IDs in Type table:", missing_type_ids)

Numeric type IDs in Item: [2.0, 10.0, 13.0, 19.0, 34.0, 44.0, 45.0, 61.0, 63.0, 64.0, 72.0, 76.0, 82.0, 84.0, 91.0, 92.0, 93.0]
Missing IDs in Type table: set()

In [97]:
print(type_df)

    AttractionTypeId                  AttractionType
0                  2                   Ancient Ruins
1                 10                         Ballets
2                 13                         Beaches
3                 19                 Caverns & Caves
4                 34           Flea & Street Markets
5                 44                  Historic Sites
6                 45                 History Museums
7                 61                  National Parks
8                 63         Nature & Wildlife Areas
9                 64                   Neighborhoods
10                72  Points of Interest & Landmarks
11                76                 Religious Sites
12                82                            Spas
13                84              Speciality Museums
14                91                        Volcanos
15                92                     Water Parks
16                93                      Waterfalls

In [98]:
print(item["AttractionTypeClean"].unique())

['13' '63' '76' '72' '93' '92' '61' '64' '82' '91' '84' '19' '34' '10' '2'
 '45' '44' 'Temple' 'Beach' 'Park' 'Museum' 'Market']

In [99]:
print("Missing AttractionTypeClean values:", item["AttractionTypeClean"].isna().sum())

Missing AttractionTypeClean values: 0

In [100]:
print("Total attraction rows:", len(item))
print("Unique Attraction IDs:", item["AttractionId"].nunique())
print("Duplicate Attraction IDs:", item["AttractionId"].duplicated().sum())

Total attraction rows: 1698
Unique Attraction IDs: 1698
Duplicate Attraction IDs: 0

In [101]:
missing_attractions = set(transaction["AttractionId"]) - set(item["AttractionId"])

print("Attraction IDs in transactions:", transaction["AttractionId"].nunique())
print("Attraction IDs in item:", item["AttractionId"].nunique())
print("Missing attraction IDs:", missing_attractions)

Attraction IDs in transactions: 30
Attraction IDs in item: 1698
Missing attraction IDs: set()

In [102]:
print("Total transaction rows:", len(transaction))
print("Duplicate transaction rows:", transaction.duplicated().sum())

Total transaction rows: 52930
Duplicate transaction rows: 0

In [103]:
print(transaction.dtypes)

TransactionId    int64
UserId           int64
VisitYear        int64
VisitMonth       int64
VisitMode        int64
AttractionId     int64
Rating           int64
dtype: object

In [104]:
print(user.dtypes)

UserId           int64
ContinentId      int64
RegionId         int64
CountryId        int64
CityId         float64
dtype: object

In [105]:
print(city.dtypes)

CityId        int64
CityName     object
CountryId     int64
dtype: object

In [106]:
print(country.dtypes)

CountryId     int64
Country      object
RegionId      int64
dtype: object

In [107]:
print(region.dtypes)

Region         object
RegionId        int64
ContinentId     int64
dtype: object

In [108]:
print(continent.dtypes)

ContinentId     int64
Continent      object
dtype: object

In [109]:
print(mode.dtypes)

VisitModeId     int64
VisitMode      object
dtype: object

In [110]:
print(type_df.dtypes)

AttractionTypeId     int64
AttractionType      object
dtype: object

In [111]:
# Recreate the final merged dataset

# Merge Transaction with User
df = transaction.merge(
    user,
    on="UserId",
    how="left"
)

# Rename and remove duplicate CountryId
if "CountryId_x" in df.columns and "CountryId_y" in df.columns:
    df = df.rename(columns={"CountryId_y": "CountryId"})
    df = df.drop(columns=["CountryId_x"])

# Add city information
df = df.merge(
    city[["CityId", "CityName", "CountryId"]],
    on="CityId",
    how="left",
    suffixes=("", "_city")
)

# Add country information
df = df.merge(
    country[["CountryId", "Country", "RegionId"]],
    on="CountryId",
    how="left",
    suffixes=("", "_country")
)

# Add region information
df = df.merge(
    region[["RegionId", "Region", "ContinentId"]],
    on="RegionId",
    how="left",
    suffixes=("", "_region")
)

# Add continent information
df = df.merge(
    continent[["ContinentId", "Continent"]],
    on="ContinentId",
    how="left"
)

# Add visit mode name
df = df.merge(
    mode[["VisitModeId", "VisitMode"]],
    left_on="VisitMode",
    right_on="VisitModeId",
    how="left"
)

# Add attraction information
df = df.merge(
    item[[
        "AttractionId",
        "AttractionCityId",
        "AttractionTypeClean",
        "Attraction",
        "AttractionAddress"
    ]],
    on="AttractionId",
    how="left"
)

print("Final dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Final dataset shape: (52930, 24)

Columns:
['TransactionId', 'UserId', 'VisitYear', 'VisitMonth', 'VisitMode_x', 'AttractionId', 'Rating', 'ContinentId', 'RegionId', 'CountryId', 'CityId', 'CityName', 'CountryId_city', 'Country', 'RegionId_country', 'Region', 'ContinentId_region', 'Continent', 'VisitModeId', 'VisitMode_y', 'AttractionCityId', 'AttractionTypeClean', 'Attraction', 'AttractionAddress']

In [112]:
# Clean duplicate columns from the merged dataframe

df = df.drop(
    columns=[
        "CountryId_city",
        "RegionId_country",
        "ContinentId_region",
        "VisitModeId"
    ],
    errors="ignore"
)

# Rename VisitMode columns
df = df.rename(
    columns={
        "VisitMode_x": "VisitModeId",
        "VisitMode_y": "VisitMode"
    }
)

print("Clean final dataset shape:", df.shape)

print("\nFinal columns:")
print(df.columns.tolist())

print("\nTotal missing values:", df.isnull().sum().sum())

Clean final dataset shape: (52930, 20)

Final columns:
['TransactionId', 'UserId', 'VisitYear', 'VisitMonth', 'VisitModeId', 'AttractionId', 'Rating', 'ContinentId', 'RegionId', 'CountryId', 'CityId', 'CityName', 'Country', 'Region', 'Continent', 'VisitMode', 'AttractionCityId', 'AttractionTypeClean', 'Attraction', 'AttractionAddress']

Total missing values: 16

In [113]:
missing_values = df.isnull().sum()

missing_values = missing_values[
    missing_values > 0
].sort_values(ascending=False)

print("Columns with missing values:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

Columns with missing values:
CityId      8
CityName    8
dtype: int64

Total missing values: 16

In [114]:
missing_city_rows = df[
    df["CityId"].isna() | df["CityName"].isna()
]

print("Rows with missing city information:")
display(
    missing_city_rows[
        [
            "TransactionId",
            "UserId",
            "CountryId",
            "Country",
            "RegionId",
            "Region",
            "ContinentId",
            "Continent",
            "CityId",
            "CityName"
        ]
    ]
)

Rows with missing city information:

,TransactionId,UserId,CountryId,Country,RegionId,Region,ContinentId,Continent,CityId,CityName
7134,10437,7175,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
21190,33604,56972,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
22283,35006,17595,22,South Africa,4,Southern Africa,1,Africa,NaN,NaN
26249,42487,56972,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
31689,67298,67461,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
34600,71286,56972,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
34799,71574,7175,135,Switzerland,17,Central Europe,5,Europe,NaN,NaN
36610,74011,17595,22,South Africa,4,Southern Africa,1,Africa,NaN,NaN

In [115]:
df["CityName"] = df["CityName"].fillna("Unknown City")
df["CityId"] = df["CityId"].fillna(-1)

print("Missing values after handling city data:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nTotal missing values:", df.isnull().sum().sum())

Missing values after handling city data:
Series([], dtype: int64)

Total missing values: 0

In [116]:
# Create VisitDate column
df["VisitDate"] = pd.to_datetime(
    df["VisitYear"].astype(str) + "-" +
    df["VisitMonth"].astype(str) + "-01",
    errors="coerce"
)

# Convert VisitMonth to numeric
df["VisitMonthNum"] = pd.to_numeric(
    df["VisitMonth"],
    errors="coerce"
)

# Create ML-ready dataset
ml_df = df[[
    "UserId",
    "VisitYear",
    "VisitMonthNum",
    "VisitModeId",
    "AttractionId",
    "Rating",
    "ContinentId",
    "RegionId",
    "CountryId",
    "CityId",
    "AttractionCityId",
    "AttractionTypeClean"
]].copy()

print("ML dataset shape:", ml_df.shape)

print("\nML dataset columns:")
print(ml_df.columns.tolist())

print("\nTotal missing values:", ml_df.isnull().sum().sum())

ML dataset shape: (52930, 12)

ML dataset columns:
['UserId', 'VisitYear', 'VisitMonthNum', 'VisitModeId', 'AttractionId', 'Rating', 'ContinentId', 'RegionId', 'CountryId', 'CityId', 'AttractionCityId', 'AttractionTypeClean']

Total missing values: 0

In [117]:
from sklearn.model_selection import train_test_split

# Classification target
y_cls = ml_df["VisitModeId"]

# Classification features
X_cls = ml_df.drop(
    columns=[
        "VisitModeId",
        "Rating"
    ]
)

# Split the data
X_cls_train, X_cls_test, y_cls_train, y_cls_test = train_test_split(
    X_cls,
    y_cls,
    test_size=0.2,
    random_state=42,
    stratify=y_cls
)

print("Classification training data:", X_cls_train.shape)
print("Classification testing data:", X_cls_test.shape)

print("\nNumber of classes:", y_cls.nunique())
print("Classes:", sorted(y_cls.unique()))

Classification training data: (42344, 10)
Classification testing data: (10586, 10)

Number of classes: 5
Classes: [1, 2, 3, 4, 5]

In [118]:
from sklearn.ensemble import RandomForestClassifier

# Create the classification model
clf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)

# Train the model
clf_model.fit(X_cls_train, y_cls_train)

# Predictions
y_cls_pred = clf_model.predict(X_cls_test)

print("Random Forest Classification Model trained successfully.")

Random Forest Classification Model trained successfully.

In [119]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Calculate evaluation metrics
accuracy = accuracy_score(y_cls_test, y_cls_pred)

precision = precision_score(
    y_cls_test,
    y_cls_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_cls_test,
    y_cls_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_cls_test,
    y_cls_pred,
    average="weighted",
    zero_division=0
)

print("Classification Model Evaluation")
print("--------------------------------")
print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1 Score :", round(f1, 4))

print("\nDetailed Classification Report:")
print(classification_report(
    y_cls_test,
    y_cls_pred,
    zero_division=0
))

Classification Model Evaluation
--------------------------------
Accuracy : 0.5278
Precision: 0.5238
Recall   : 0.5278
F1 Score : 0.5107

Detailed Classification Report:
              precision    recall  f1-score   support

           1       0.60      0.26      0.37       125
           2       0.54      0.73      0.62      4324
           3       0.54      0.49      0.52      3043
           4       0.46      0.32      0.37      2189
           5       0.55      0.23      0.33       905

    accuracy                           0.53     10586
   macro avg       0.54      0.41      0.44     10586
weighted avg       0.52      0.53      0.51     10586

In [120]:
# Create classification dataset with additional features

classification_df = ml_df.copy()

# User's total number of visits
classification_df["UserVisitCount"] = (
    classification_df.groupby("UserId")["UserId"]
    .transform("count")
)

# Average rating given by the user
classification_df["UserAverageRating"] = (
    classification_df.groupby("UserId")["Rating"]
    .transform("mean")
)

# Attraction average rating
classification_df["AttractionAverageRating"] = (
    classification_df.groupby("AttractionId")["Rating"]
    .transform("mean")
)

print("Feature-engineered dataset shape:", classification_df.shape)

print("\nNew features:")
print([
    "UserVisitCount",
    "UserAverageRating",
    "AttractionAverageRating"
])

Feature-engineered dataset shape: (52930, 15)

New features:
['UserVisitCount', 'UserAverageRating', 'AttractionAverageRating']

In [121]:
# Create attraction-level dataset for recommendation system

attraction_df = df[
    [
        "AttractionId",
        "Attraction",
        "AttractionTypeClean",
        "CityName",
        "Country",
        "Region",
        "Continent",
        "Rating"
    ]
].copy()

# Calculate average rating for each attraction
attraction_ratings = (
    attraction_df
    .groupby("AttractionId")["Rating"]
    .mean()
    .reset_index()
    .rename(columns={"Rating": "AverageRating"})
)

# Keep one row per attraction
attraction_info = attraction_df.drop_duplicates(
    subset="AttractionId"
)

# Merge average ratings
attraction_info = attraction_info.drop(columns=["Rating"]).merge(
    attraction_ratings,
    on="AttractionId",
    how="left"
)

print("Total unique attractions:", attraction_info.shape[0])

print("\nRecommendation dataset preview:")
display(attraction_info.head())

Total unique attractions: 30

Recommendation dataset preview:

,AttractionId,Attraction,AttractionTypeClean,CityName,Country,Region,Continent,AverageRating
0,640,Sacred Monkey Forest Sanctuary,63,Guildford,United Kingdom,Western Europe,Europe,4.267086
1,841,Waterbom Bali,92,Melbourne,Australia,Australia,Australia & Oceania,4.646601
2,673,Seminyak Beach,13,Melbourne,Australia,Australia,Australia & Oceania,3.800618
3,481,Nusa Dua Beach,13,Poole,United Kingdom,Western Europe,Europe,4.275665
4,650,Sanur Beach,13,Gold Coast,Australia,Australia,Australia & Oceania,3.976347

In [122]:
from sklearn.model_selection import train_test_split

# Regression target
y_reg = ml_df["Rating"]

# Regression features
X_reg = ml_df.drop(
    columns=[
        "Rating",
        "VisitModeId"
    ]
)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

print("Regression training data:", X_train.shape)
print("Regression testing data:", X_test.shape)

Regression training data: (42344, 10)
Regression testing data: (10586, 10)

In [123]:
from sklearn.linear_model import LinearRegression

# Create the model
linear_reg_model = LinearRegression()

# Train the model
linear_reg_model.fit(X_train, y_train)

# Make predictions
linear_y_pred = linear_reg_model.predict(X_test)

print("Linear Regression model trained successfully.")
print("First 10 predictions:", linear_y_pred[:10])

Linear Regression model trained successfully.
First 10 predictions: [4.26808346 4.3143652  3.92509913 4.13149631 4.22825908 4.3784386
 3.80925165 4.01551379 4.16369304 3.74003932]

In [124]:
from sklearn.metrics import mean_squared_error, r2_score

# Calculate evaluation metrics
linear_mse = mean_squared_error(y_test, linear_y_pred)
linear_r2 = r2_score(y_test, linear_y_pred)

print("Linear Regression Evaluation")
print("----------------------------")
print("Mean Squared Error (MSE):", round(linear_mse, 4))
print("R² Score:", round(linear_r2, 4))

Linear Regression Evaluation
----------------------------
Mean Squared Error (MSE): 0.9031
R² Score: 0.0411

In [125]:
from sklearn.ensemble import RandomForestRegressor

# Create Random Forest Regression model
rf_reg_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_reg_model.fit(X_train, y_train)

# Make predictions
rf_y_pred = rf_reg_model.predict(X_test)

print("Random Forest Regression model trained successfully.")
print("First 10 predictions:", rf_y_pred[:10])

Random Forest Regression model trained successfully.
First 10 predictions: [4.265      4.095      3.62214286 3.975      3.765      4.005
 4.61016667 4.078      4.245      4.62      ]

In [126]:
# Evaluate Random Forest Regression
rf_mse = mean_squared_error(y_test, rf_y_pred)
rf_r2 = r2_score(y_test, rf_y_pred)

print("Random Forest Regression Evaluation")
print("-----------------------------------")
print("Mean Squared Error (MSE):", round(rf_mse, 4))
print("R² Score:", round(rf_r2, 4))

Random Forest Regression Evaluation
-----------------------------------
Mean Squared Error (MSE): 0.8374
R² Score: 0.1109

In [127]:
# Compare Regression Models

if rf_r2 > linear_r2:
    best_reg_model = rf_reg_model
    best_reg_predictions = rf_y_pred
    best_reg_name = "Random Forest Regression"
    best_reg_mse = rf_mse
    best_reg_r2 = rf_r2
else:
    best_reg_model = linear_reg_model
    best_reg_predictions = linear_y_pred
    best_reg_name = "Linear Regression"
    best_reg_mse = linear_mse
    best_reg_r2 = linear_r2

print("Best Regression Model:", best_reg_name)
print("Best MSE:", round(best_reg_mse, 4))
print("Best R² Score:", round(best_reg_r2, 4))

Best Regression Model: Random Forest Regression
Best MSE: 0.8374
Best R² Score: 0.1109

In [128]:
# Final Classification Model Results

best_cls_model = clf_model
best_cls_predictions = y_cls_pred

print("Best Classification Model: Random Forest Classifier")
print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1 Score :", round(f1, 4))

Best Classification Model: Random Forest Classifier
Accuracy : 0.5278
Precision: 0.5238
Recall   : 0.5278
F1 Score : 0.5107

In [129]:
# Check available columns for recommendation system
print(attraction_info.columns.tolist())
print("\nAttraction dataset shape:", attraction_info.shape)

['AttractionId', 'Attraction', 'AttractionTypeClean', 'CityName', 'Country', 'Region', 'Continent', 'AverageRating']

Attraction dataset shape: (30, 8)

In [130]:
# Create recommendation features

recommendation_df = attraction_info.copy()

# Combine attraction characteristics into one feature
recommendation_df["Features"] = (
    recommendation_df["AttractionTypeClean"].astype(str) + " " +
    recommendation_df["Country"].astype(str) + " " +
    recommendation_df["Region"].astype(str) + " " +
    recommendation_df["Continent"].astype(str)
)

print("Recommendation dataset shape:", recommendation_df.shape)

print("\nSample recommendation features:")
display(
    recommendation_df[
        [
            "Attraction",
            "AttractionTypeClean",
            "Country",
            "Features",
            "AverageRating"
        ]
    ].head()
)

Recommendation dataset shape: (30, 9)

Sample recommendation features:

,Attraction,AttractionTypeClean,Country,Features,AverageRating
0,Sacred Monkey Forest Sanctuary,63,United Kingdom,63 United Kingdom Western Europe Europe,4.267086
1,Waterbom Bali,92,Australia,92 Australia Australia Australia & Oceania,4.646601
2,Seminyak Beach,13,Australia,13 Australia Australia Australia & Oceania,3.800618
3,Nusa Dua Beach,13,United Kingdom,13 United Kingdom Western Europe Europe,4.275665
4,Sanur Beach,13,Australia,13 Australia Australia Australia & Oceania,3.976347

In [131]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Convert recommendation features into numerical vectors
tfidf = TfidfVectorizer()

feature_matrix = tfidf.fit_transform(
    recommendation_df["Features"]
)

# Calculate similarity between attractions
similarity_matrix = cosine_similarity(feature_matrix)

print("Feature matrix shape:", feature_matrix.shape)
print("Similarity matrix shape:", similarity_matrix.shape)

Feature matrix shape: (30, 39)
Similarity matrix shape: (30, 30)

In [132]:
def recommend_attractions(attraction_name, top_n=5):
    
    # Find the attraction
    matches = recommendation_df[
        recommendation_df["Attraction"].str.lower()
        == attraction_name.lower()
    ]
    
    if matches.empty:
        return "Attraction not found."
    
    # Get attraction index
    idx = matches.index[0]
    
    # Get similarity scores
    similarity_scores = list(
        enumerate(similarity_matrix[idx])
    )
    
    # Sort by similarity score
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )
    
    # Remove the selected attraction
    similarity_scores = [
        score for score in similarity_scores
        if score[0] != idx
    ]
    
    # Get top similar attractions
    top_indices = [
        score[0]
        for score in similarity_scores[:top_n]
    ]
    
    # Create recommendation results
    recommendations = recommendation_df.iloc[
        top_indices
    ][
        [
            "Attraction",
            "AttractionTypeClean",
            "Country",
            "Region",
            "AverageRating"
        ]
    ].copy()
    
    # Sort recommendations by rating
    recommendations = recommendations.sort_values(
        by="AverageRating",
        ascending=False
    )
    
    return recommendations


print("Recommendation function created successfully.")

Recommendation function created successfully.

In [133]:
# Test the recommendation system

recommendations = recommend_attractions(
    "Waterbom Bali",
    top_n=5
)

print("Top 5 Recommended Attractions:")
display(recommendations)

Top 5 Recommended Attractions:

,Attraction,AttractionTypeClean,Country,Region,AverageRating
0,Sacred Monkey Forest Sanctuary,63,United Kingdom,Western Europe,4.267086
16,Goa Cina Beach,13,Australia,Australia,4.092593
4,Sanur Beach,13,Australia,Australia,3.976347
2,Seminyak Beach,13,Australia,Australia,3.800618
9,Kuta Beach - Bali,13,Australia,Australia,3.415190

In [134]:
def evaluate_recommendations(attraction_name, top_n=5):

    matches = recommendation_df[
        recommendation_df["Attraction"].str.lower()
        == attraction_name.lower()
    ]

    if matches.empty:
        print("Attraction not found.")
        return

    idx = matches.index[0]

    similarity_scores = list(
        enumerate(similarity_matrix[idx])
    )

    # Remove selected attraction
    similarity_scores = [
        (i, score)
        for i, score in similarity_scores
        if i != idx
    ]

    # Sort by similarity
    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )[:top_n]

    results = []

    for i, score in similarity_scores:
        results.append({
            "Attraction": recommendation_df.iloc[i]["Attraction"],
            "SimilarityScore": round(score, 4),
            "AverageRating": round(
                recommendation_df.iloc[i]["AverageRating"], 4
            )
        })

    return pd.DataFrame(results)


evaluation_results = evaluate_recommendations(
    "Waterbom Bali",
    top_n=5
)

print("Recommendation Evaluation:")
display(evaluation_results)

Recommendation Evaluation:

                       Attraction  SimilarityScore  AverageRating
0                  Seminyak Beach           0.8747         3.8006
1                     Sanur Beach           0.8747         3.9763
2               Kuta Beach - Bali           0.8747         3.4152
3                  Goa Cina Beach           0.8747         4.0926
4  Sacred Monkey Forest Sanctuary           0.0000         4.2671

In [135]:
# Final Project Model Summary

model_summary = pd.DataFrame({
    "Task": [
        "Regression",
        "Regression",
        "Classification",
        "Recommendation System"
    ],
    "Model/System": [
        "Linear Regression",
        "Random Forest Regression",
        "Random Forest Classifier",
        "Content-Based Recommendation"
    ],
    "Primary Metric": [
        "R² Score",
        "R² Score",
        "Accuracy",
        "Cosine Similarity"
    ],
    "Score": [
        round(linear_r2, 4),
        round(rf_r2, 4),
        round(accuracy, 4),
        "Up to 0.8747"
    ]
})

print("Final Model Summary:")
display(model_summary)

Final Model Summary:

,Task,Model/System,Primary Metric,Score
0,Regression,Linear Regression,R² Score,0.0411
1,Regression,Random Forest Regression,R² Score,0.1109
2,Classification,Random Forest Classifier,Accuracy,0.5278
3,Recommendation System,Content-Based Recommendation,Cosine Similarity,Up to 0.8747

In [136]:
# Final Project Insights

print("TOURISM EXPERIENCE ANALYTICS - FINAL INSIGHTS")
print("=============================================\n")

print("1. Regression Analysis")
print(
    f"   Best Model: {best_reg_name}"
)
print(
    f"   Best R² Score: {best_reg_r2:.4f}"
)
print(
    f"   Best MSE: {best_reg_mse:.4f}"
)

print("\n2. Classification Analysis")
print("   Best Model: Random Forest Classifier")
print(
    f"   Accuracy: {accuracy:.4f}"
)
print(
    f"   F1 Score: {f1:.4f}"
)

print("\n3. Recommendation System")
print("   Method: Content-Based Recommendation")
print("   Similarity Method: TF-IDF + Cosine Similarity")
print("   Highest observed similarity: 0.8747")

print("\n4. Overall Conclusion")
print(
    "   The project successfully analyzes tourism experience data "
    "and provides rating prediction, visit mode classification, "
    "and attraction recommendations."
)

TOURISM EXPERIENCE ANALYTICS - FINAL INSIGHTS
=============================================

1. Regression Analysis
   Best Model: Random Forest Regression
   Best R² Score: 0.1109
   Best MSE: 0.8374

2. Classification Analysis
   Best Model: Random Forest Classifier
   Accuracy: 0.5278
   F1 Score: 0.5107

3. Recommendation System
   Method: Content-Based Recommendation
   Similarity Method: TF-IDF + Cosine Similarity
   Highest observed similarity: 0.8747

4. Overall Conclusion
   The project successfully analyzes tourism experience data and provides rating prediction, visit mode classification, and attraction recommendations.

In [137]:
import joblib

# Save Regression Model
joblib.dump(
    best_reg_model,
    "best_regression_model.pkl"
)

# Save Classification Model
joblib.dump(
    best_cls_model,
    "best_classification_model.pkl"
)

# Save Recommendation Data
joblib.dump(
    recommendation_df,
    "recommendation_data.pkl"
)

# Save Similarity Matrix
joblib.dump(
    similarity_matrix,
    "similarity_matrix.pkl"
)

print("All project models and recommendation files saved successfully!")

All project models and recommendation files saved successfully!